export const trendingSeries = [
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/oGsh97JAA6LYu92B6TEswrjac8W.jpg',
        id: 248852,
        name: 'UNTAMED',
        original_name: 'UNTAMED',
        overview:
            "In the vast expanse of Yosemite National Park, a woman's death draws a federal agent into lawless terrain — where nature obeys no rules but its own.",
        poster_path: 'https://image.tmdb.org/t/p/w342/tclYY8RGieQwkJXDxZGf505Zybr.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [9648, 18],
        popularity: 189.4464,
        first_air_date: '2025-07-17',
        vote_average: 7.4,
        vote_count: 91,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/htGeuCcNhlBe8GTx3izKOsd8frw.jpg',
        id: 207468,
        name: 'Kaiju No. 8',
        original_name: '怪獣８号',
        overview:
            "In a world plagued by creatures known as Kaiju, Kafka Hibino aspired to enlist in The Defense Force. He makes a promise to enlist with his childhood friend, Mina Ashiro. Soon, life takes them in separate ways. While employed cleaning up after Kaiju battles, Kafka meets Reno Ichikawa. Reno's determination to join The Defense Force reawakens Kafka's promise to join Mina and protect humanity.",
        poster_path: 'https://image.tmdb.org/t/p/w342/PDe8WZHxH6XxM6Buxoo99aQrgw.jpg',
        media_type: 'tv',
        original_language: 'ja',
        genre_ids: [16, 10759, 10765],
        popularity: 130.2369,
        first_air_date: '2024-04-13',
        vote_average: 8.6,
        vote_count: 563,
        origin_country: ['JP'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
        id: 66732,
        name: 'Stranger Things',
        original_name: 'Stranger Things',
        overview:
            'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
        poster_path: 'https://image.tmdb.org/t/p/w342/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [18, 10765, 9648],
        popularity: 158.8664,
        first_air_date: '2016-07-15',
        vote_average: 8.6,
        vote_count: 18539,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/627K48naKH2Y3Rz47Ydra4qktdI.jpg',
        id: 103516,
        name: 'Star Trek: Strange New Worlds',
        original_name: 'Star Trek: Strange New Worlds',
        overview:
            'Follow Captain Christopher Pike, Science Officer Spock and Number One in the years before Captain Kirk boarded the U.S.S. Enterprise, as they explore new worlds around the galaxy.',
        poster_path: 'https://image.tmdb.org/t/p/w342/w6KapI2JvrCkOPmQhkwYPJNjqeo.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [10765],
        popularity: 86.8467,
        first_air_date: '2022-05-05',
        vote_average: 8.078,
        vote_count: 628,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/l5jzuehwynnoEWUb9z25auHXQM.jpg',
        id: 259909,
        name: 'Dexter: Resurrection',
        original_name: 'Dexter: Resurrection',
        overview:
            "Dexter Morgan awakens from a coma to find Harrison gone without a trace. Realizing the weight of what he put his son through, Dexter sets out for New York City, determined to find him and make things right. But closure won't come easy. When Miami Metro's Angel Batista arrives with questions, Dexter realizes his past is catching up to him fast. As father and son navigate their own darkness in the city that never sleeps, they soon find themselves deeper than they ever imagined - and that the only way out is together.",
        poster_path: 'https://image.tmdb.org/t/p/w342/hIawSocuwqgNeRf3JuKuxgMHmSC.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [80, 18],
        popularity: 89.4578,
        first_air_date: '2025-07-13',
        vote_average: 9.023,
        vote_count: 65,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/2meX1nMdScFOoV4370rqHWKmXhY.jpg',
        id: 93405,
        name: 'Squid Game',
        original_name: '오징어 게임',
        overview:
            "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
        poster_path: 'https://image.tmdb.org/t/p/w342/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg',
        media_type: 'tv',
        original_language: 'ko',
        genre_ids: [10759, 9648, 18],
        popularity: 433.201,
        first_air_date: '2021-09-17',
        vote_average: 7.865,
        vote_count: 16425,
        origin_country: ['KR'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/24tNHi5UJHATn61FTo9QiyQzbMH.jpg',
        id: 90802,
        name: 'The Sandman',
        original_name: 'The Sandman',
        overview:
            'After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him and restore his power.',
        poster_path: 'https://image.tmdb.org/t/p/w342/dhbqyYjLfTNAHodDDjDELzwO6F4.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [10765, 18, 10759],
        popularity: 73.3076,
        first_air_date: '2022-08-05',
        vote_average: 7.931,
        vote_count: 2255,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/jCQV3rHNbgHKo3N4G6CARbVEjPV.jpg',
        id: 194766,
        name: 'The Summer I Turned Pretty',
        original_name: 'The Summer I Turned Pretty',
        overview:
            "Every summer, Belly and her family head to the Fishers’ beach house in Cousins. Every summer is the same ... until Belly turns sixteen. Relationships will be tested, painful truths will be revealed, and Belly will be forever changed. It’s a summer of first love, first heartbreak and growing up — it's the summer she turns pretty.",
        poster_path: 'https://image.tmdb.org/t/p/w342/s85u6WqkfkVBOrWDMKrefnU1g1n.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [18],
        popularity: 294.8939,
        first_air_date: '2022-06-16',
        vote_average: 8.2,
        vote_count: 839,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/lqaT9mIxcVJs9QSUf0hdy0zW68C.jpg',
        id: 248830,
        name: 'Stick',
        original_name: 'Stick',
        overview:
            'Pryce Cahill was headed for golf greatness when an on-course meltdown derailed his career. Now struggling to stay afloat, he goes all in to mentor Santi—a teenage phenom with immense potential—and maybe save himself.',
        poster_path: 'https://image.tmdb.org/t/p/w342/y8EWrf5Ry1WmYksWT7MOPWexvr5.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [35, 18],
        popularity: 65.2389,
        first_air_date: '2025-06-03',
        vote_average: 7.073,
        vote_count: 41,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/mcU5nwUqPJB6GeElDhKA68LKhqD.jpg',
        id: 253372,
        name: 'The Institute',
        original_name: 'The Institute',
        overview:
            'When 14 year old genius Luke Ellis is kidnapped, he awakens at The Institute, a facility full of children who all got there the same way he did, and who are all possessed of unusual abilities. In a nearby town, haunted former police officer Tim Jamieson has come looking to start a new life, but the peace and quiet won’t last, as his story and Luke’s are destined to collide.',
        poster_path: 'https://image.tmdb.org/t/p/w342/7JXZdWifaa6wL0XLRi0GJOlOA8y.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [9648, 10765],
        popularity: 80.2134,
        first_air_date: '2025-07-13',
        vote_average: 7.903,
        vote_count: 31,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/uNTrRKIOyKYISthoeizghtXPEOK.jpg',
        id: 240411,
        name: 'Dan Da Dan',
        original_name: 'ダンダダン',
        overview:
            'In a bet to prove whether ghosts or aliens exist, two high schoolers face terrifying paranormal threats, gain superpowers and maybe even fall in love?!',
        poster_path: 'https://image.tmdb.org/t/p/w342/tiF5I6wF6tEUy39gmNtw3G1GYyz.jpg',
        media_type: 'tv',
        original_language: 'ja',
        genre_ids: [16, 10759, 35, 10765],
        popularity: 103.1961,
        first_air_date: '2024-10-04',
        vote_average: 8.652,
        vote_count: 565,
        origin_country: ['JP'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/7NNNXo0qG2SqH4JoG7GPvJ2hzes.jpg',
        id: 93740,
        name: 'Foundation',
        original_name: 'Foundation',
        overview:
            'Follow a band of exiles on their monumental journey to save humanity and rebuild civilization amid the fall of the Galactic Empire.',
        poster_path: 'https://image.tmdb.org/t/p/w342/tg9I5pOY4M9CKj8U0cxVBTsm5eh.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [10765, 18],
        popularity: 96.2587,
        first_air_date: '2021-09-23',
        vote_average: 7.754,
        vote_count: 1419,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/Ao5pBFuWY32cVuh6iYjEjZMEscN.jpg',
        id: 60625,
        name: 'Rick and Morty',
        original_name: 'Rick and Morty',
        overview:
            "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
        poster_path: 'https://image.tmdb.org/t/p/w342/WGRQ8FpjkDTzivQJ43t94bOuY0.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [16, 35, 10765, 10759],
        popularity: 212.8697,
        first_air_date: '2013-12-02',
        vote_average: 8.689,
        vote_count: 10299,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/41neXsH222hV2zrsTyw8h7javon.jpg',
        id: 2190,
        name: 'South Park',
        original_name: 'South Park',
        overview:
            'Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.',
        poster_path: 'https://image.tmdb.org/t/p/w342/xJnbMTrJ2fl1AXAKx34U4BPvOhs.jpg',
        media_type: 'tv',
        original_language: 'en',
        genre_ids: [16, 35],
        popularity: 153.4641,
        first_air_date: '1997-08-13',
        vote_average: 8.4,
        vote_count: 4573,
        origin_country: ['US'],
    },
    {
        adult: false,
        backdrop_path: 'https://image.tmdb.org/t/p/w342/x0rCzswwYCEm4HM3c8v8L8olB2X.jpg',
        id: 232402,
        name: 'S Line',
        original_name: 'S라인',
        overview:
            'A young woman with the ability to see mysterious red connections between lovers discovers her secret gift is no longer unique when special glasses granting similar powers appear on the black market.',
        poster_path: 'https://image.tmdb.org/t/p/w342/7TGolwcia6AI6uvInBOoedAi9Il.jpg',
        media_type: 'tv',
        original_language: 'ko',
        genre_ids: [10765, 18, 9648],
        popularity: 155.716,
        first_air_date: '2025-07-11',
        vote_average: 7.741,
        vote_count: 54,
        origin_country: ['KR'],
    },
]
    .filter((movie) => movie.vote_count)
    .sort((a, b) => {
        if (!a.vote_count || !b.vote_count) return -1;
        return b.vote_count - a.vote_count;
    });
